[build]
command = "yarn build"
functions = "functions/"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[context.production.environment]
INDEX_ALGOLIA = "true"
ADD_PREFIX = "true"

[context.deploy-preview.environment]
INDEX_ALGOLIA = "false"
DEPLOY_PREVIEW = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://www.prisma.io"
